# Generated by Django 2.0.3 on 2018-03-12 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_user_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='photo',
            new_name='img_profile',
        ),
    ]
